/**
 * Aspose.Slides for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

var assert = require('assert');
import * as model from "../sdk/model";
import { PostSlidesPipelineRequest, /*PostSlideSaveAsRequest, */SlidesApi } from "../sdk/api";
/*import { TestInitializer } from "./testInitializer";*/

describe("Additional tests for pipeline", () => {
    it("multiple files upload", () => {
        const config = require("../testConfig.json");
        const fs = require('fs');
        const api = new SlidesApi(config.AppSid, config.AppKey, config.BaseUrl, config.AuthBaseUrl, config.debug);
        const request = new PostSlidesPipelineRequest();
        const file1 : model.RequestInputFile = { type: model.InputFile.TypeEnum.Request, index: 0 };
        const file2 : model.RequestInputFile = { type: model.InputFile.TypeEnum.Request, index: 1 };
        const task : model.Save = {
            format: model.Save.FormatEnum.Pptx,
            output: { type: model.OutputFile.TypeEnum.Response },
            type: model.Task.TypeEnum.Save
        };
        request.pipeline = { input: { templateData: file1, template: file2 }, tasks: [ task ] };
        request.files = [
            fs.createReadStream("TestData/TemplatingCVDataWithBase64.xml"),
            fs.createReadStream("TestData/TemplateCV.pptx")
        ];
        
        return api.postSlidesPipeline(request).then((result) => {
            assert.equal(200, result.response.statusCode);
        });
    });
});

/*unstable test
describe("Tests for timeout configuration parameter", () => {
    it("convert slide to svg", () => {
        return TestInitializer.initialize("postSlideSaveAs", null, null).then(() => {
            const config = require("../testConfig.json");
            const fs = require('fs');
            const api = new SlidesApi(config.AppSid, config.AppKey, config.BaseUrl, config.AuthBaseUrl, config.debug, 1);
            const request = new PostSlideSaveAsRequest();
            request.format = "svg";
            request.name = "test.ppt";
            request.folder = "TempSlidesSDK";
            request.password = "password";
            request.slideIndex = 1;
            return api.postSlideSaveAs(request)
                .then((result) => {
                    assert.equal(200, result.response.statusCode);
                    assert.fail("must have failed because of timeout");
                }).catch((e) => {
                });
        }).catch((err) => assert.fail(err));
    });
});*/
